# On part d'une version légère de Python
FROM python:3.9-slim

# On se met dans le dossier /app du conteneur
WORKDIR /app

# On installe Flask
RUN pip install flask

# On lance l'application
CMD ["python", "app.py"]
